name: sample_data
description: A new Flutter package that generated random sample data to test your application.
version: 1.0.0
homepage: https://github.com/ibhavikmakwana/sample_data

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - asset/
    - asset/kids/